### ISSUE TITLE
Setting up Spring profiles

### ISSUE THREAD

**Issue by arsgsg1** [classvar/classvar-user-backend#1]
![image](https://user-images.githubusercontent.com/25299428/127334881-7d3db81f-4a9a-449b-9bb0-8e91f7176ccf.png)

![image](https://user-images.githubusercontent.com/25299428/127334769-6daddf23-1ba9-460b-8973-0de70047a03b.png)

환경에 따라 local (로컬 개발환경), prod (실서버 환경)으로 yml 파일을 구분하여 활성화 설정

**Comment by arsgsg1** [comment]
참고 https://jojoldu.tistory.com/547

**Comment by seongbin9786** [comment]
이슈명 영문으로 변경했습니다

**Comment by seongbin9786** [comment]
이미 처리된 이슈이므로 종결합니다.

**Comment by seongbin9786** [comment]
이미 처리된 이슈이므로 종결합니다.
