### ISSUE TITLE
Write Exam Service

### ISSUE THREAD

**Issue by arsgsg1** [classvar/classvar-user-backend#14]
### 세부 목적 (주 목적은 이슈 이름으로.)

도메인 로직과 인프라 계층, 컨트롤러 계층의 뼈대 코드 작성

### 예상 난이도는?

Easy

### 개발 계획

- [ ] Infra 계층 구현
- [ ] Domain 로직 작성
- [ ] Controller 계층 구현

**Comment by seongbin9786** [comment]
이미 구현이 완료된 이슈이므로 종결합니다.
