### ISSUE TITLE
Add manager domain

### ISSUE THREAD

**Issue by arsgsg1** [classvar/classvar-user-backend#47]
### 세부 목적 (주 목적은 이슈 이름으로.)

감독관 도메인의 로직을 정의합니다.
감독관 CRUD 로직, 컨트롤러, application service

### 예상 난이도는?

Easy

**Comment by arsgsg1** [comment]
+ manager 등록 시 이메일을 리스트로 받도록 변경
+ manager 등록 시 managerId를 입력받는지 **논의 필요**

**Comment by seongbin9786** [comment]
closed by merging #48
